### ISSUE TITLE
Decide on serialization method

### ISSUE THREAD

**Issue by citizen428** [lockstep/rails_new#41]
Background: [What's happening to AMS](https://github.com/rails-api/active_model_serializers#whats-happening-to-ams)

They themselves seem to suggest that [jsonapi-rb](http://jsonapi-rb.org/) could be a good alternative, so I'm interested in opinions.

Please check out the docs and provide feedback on whether or not we should move forward with this:

http://jsonapi-rb.org/guides/getting_started/rails.html

For reference: I always liked JSON API and built similar structures myself before it became a thing, so might be biased.

**Comment by roonglit** [comment]
I only use rabl. it's flexible enough for me.

**Comment by mkaschenko** [comment]
I'm ok with `jbuilder` too.

**Comment by karunsiri** [comment]
Some parts of the docs are being rewritten, but from skimming through the guide and GH repos, here are what I find useful for this handy gem that makes me +1 on this.

- There are a _serializer_ and a _deserializer_, which should make life easier when producing and consuming JSON resource. For RoR Deserializer, see https://github.com/jsonapi-rb/jsonapi-rails/blob/master/lib/jsonapi/rails/deserializable_resource.rb. The actual deserializer is here https://github.com/jsonapi-rb/jsonapi-deserializable/blob/master/lib/jsonapi/deserializable/resource/dsl.rb.
- There is _Rails_ wrapper here https://github.com/jsonapi-rb/jsonapi-rails, which includes generators and DSL for RoR
- You have to explicitly tell which resources to be serialized/deserialized with which serializer/deserializer, no guessing, head-to-desk bumping.

There probably be more benefits but hard to tell since the complete docs are still in progress.

I +1 on this change

What do you all think?

**Comment by cpariwat** [comment]
Hmm 🤔   I personally like the direction AMS is going but basically it will probably become more like  jsonapi-rb? 
I'm ok with jsonapi-rb. docs seem straightforward and plus it looks familiar for AMS users.

**Comment by citizen428** [comment]
Yeah, from what I could tell AMS is moving in the direction of `jsonapi-rb`, while at the same time saying in their own README:

> The 0.10.x version has become a huge maintenance version. We had hoped to get it in shape for a 1.0 release, but it is clear that isn't going to happen. Almost none of the maintainers from 0.8, 0.9, or earlier 0.10 are still working on AMS. 

This was what prompted me to start this discussion: if current AMS is a mess and in the future will just turn more and more into JSON API, maybe we're better of just switching to the latter anyway?

**Comment by hiattp** [comment]
I’m down for switching
