### ISSUE TITLE
Question: UUID by default?

### ISSUE THREAD

**Issue by janklimo** [lockstep/rails_new#60]
@hiattp @citizen428 I like the anonymity of UUIDs when the IDs are exposed in URLs etc. Thoughts on making them default? Can be configured in `application.rb` like `g.orm :active_record, primary_key_type: :uuid` + a migration with `enable_extension 'pgcrypto'`.

**Comment by hiattp** [comment]
I don't have a strong opinion about this other than a general preference for defaults :). It _is_ a nice obfuscation esp for apps at small scale. _But_ it's nice to reference simple numbers when debugging/pulling records up and referencing them in conversation

**Comment by citizen428** [comment]
I'm a bit indifferent on this one. I used to work on a bigger app that used UUIDs and what bothered me most in the long run was having to keep a list of UUIDs handy for e.g. testing on staging, instead of being able to remember that it's entity 37 I'm looking for. Let me throw in some further reading for everyone's perusal:

https://tomharrisonjr.com/uuid-or-guid-as-primary-keys-be-careful-7b2aa3dcb439

**Comment by janklimo** [comment]
I think all of us being indifferent with a concern or two is a reason enough to close this 😄 thanks for the feedback!
